#!/usr/bin/env node
var version = require('./package.json').version
USER_AGENT = 'zenbot/' + version
var zenbrain = require('zenbrain')
var path = require('path')
var brain = zenbrain(__dirname, 'zb')
brain.cli()