#!/usr/bin/env node
var version = require('./package.json').version
USER_AGENT = 'zenbot/' + version
var zenbrain = require('zenbrain')
var path = require('path')
if (!require('fs').existsSync(path.resolve(__dirname, 'config.js'))) {
  throw new Error('config.js not found. Please run `cp config_sample.js config.js` and try again. --Zen')
}
var brain = zenbrain(__dirname, 'zb')
brain.cli()