# ZenBot Values

env:
  # Global config
  ZENBOT_DEFAULT_SELECTOR: 'gdax.BTC-USD'
  ZENBOT_DEFAULT_STRATEGY: 'trend_ema'
  ZENBOT_SELL_STOP_PCT: '0'
  ZENBOT_BUY_STOP_PCT: '0'
  ZENBOT_PROFIT_STOP_ENABLE_PCT: '0'
  ZENBOT_PROFIT_STOP_PCT: '1'
  ZENBOT_MAX_SLIPPAGE_PCT: '5'
  ZENBOT_BUY_PCT: '99'
  ZENBOT_SELL_PCT: '99'
  ZENBOT_ORDER_ADJUST_TIME: '5000'
  ZENBOT_MAX_SELL_LOSS_PCT: '99'
  ZENBOT_MAX_BUY_LOSS_PCT: '99'
  ZENBOT_ORDER_POLL_TIME: '5000'
  ZENBOT_WAIT_FOR_SETTLEMENT: '5000'
  ZENBOT_MARKDOWN_BUY_PCT: '0'
  ZENBOT_MARKUP_SELL_PCT: '0'
  ZENBOT_ORDER_TYPE: 'maker'
  ZENBOT_POST_ONLY: 'true'
  ZENBOT_USE_FEE_ASSET: 'false'
  ZENBOT_DAYS: '14'
  ZENBOT_KEEP_LOOKBACK_PERIODS: '50000'
  ZENBOT_POLL_TRADES: '30000'
  ZENBOT_CURRENCY_CAPITAL: '1000'
  ZENBOT_ASSET_CAPITAL: '0'
  ZENBOT_SYMMETRICAL: 'false'
  ZENBOT_RSI_PERIODS: '14'
  ZENBOT_BALANCE_SNAPSHOT_PERIOD: '15m'
  ZENBOT_AVG_SLIPPAGE_PCT: '0.045'
  ZENBOT_CANCEL_AFTER: 'day'
  ZENBOT_USE_PREV_TRADES: 'false'
  ZENBOT_MIN_PREV_TRADES: '0'
  # Filter to notifier's messages for getting Commpleted Trades info.
  ZENBOT_NOTIFY_ONLY_COMPLETED_TRADES: 'false'
  ZENBOT_API_ENABLE: 'true'
  # IPv4 or IPv6 address to listen on, uses all available interfaces if omitted
  ZENBOT_API_IP: '0.0.0.0'
  ZENBOT_API_PORT: '17365'

  # GDAX exchange
  ZENBOT_GDAX_API_KEY: 'YOUR-API-KEY'
  ZENBOT_GDAX_B64_SECRET: 'YOUR-API-SECRET'
  ZENBOT_GDAX_PASSPHRASE: 'YOUR-API-PASSPHRASE'

  # Poloniex
  ZENBOT_POLONIEX_API_KEY: 'YOUR-API-KEY'
  ZENBOT_POLONIEX_SECRET: 'YOUR-API-SECRET'

  # Kraken exchange
  ZENBOT_KRAKEN_API_KEY: 'YOUR-API-KEY'
  ZENBOT_KRAKEN_SECRET: 'YOUR-API-SECRET'
  ZENBOT_KRAKEN_TOS_AGREE: 'disagree'

  # Binance exchange
  ZENBOT_BINANCE_API_KEY: 'YOUR-API-KEY'
  ZENBOT_BINANCE_SECRET: 'YOUR-API-SECRET'

  # Bittrex exchange
  ZENBOT_BITTREX_API_KEY: 'YOUR-API-KEY'
  ZENBOT_BITTREX_SECRET: 'YOUR-API-SECRET'

  # Bitfinex exchange
  ZENBOT_BITFINEX_API_KEY: 'YOUR-API-KEY'
  ZENBOT_BITFINEX_SECRET: 'YOUR-API-SECRET'
  ZENBOT_BITFINEX_WALLET: 'exchange'

  # Bitstamp exchange
  ZENBOT_BITSTAMP_API_KEY: 'YOUR-API-KEY'
  ZENBOT_BITSTAMP_SECRET: 'YOUR-API-SECRET'
  ZENBOT_BITSTAMP_CLIENT_ID: 'YOUR-CLIENT-ID'

  # Cexio exchange
  ZENBOT_CEXIO_CLIENT_ID: 'YOUR-CLIENT-ID'
  ZENBOT_CEXIO_API_KEY: 'YOUR-API-KEY'
  ZENBOT_CEXIO_SECRET: 'YOUR-API-SECRET'

  # Quadriga exchange
  ZENBOT_QUADRIGA_API_KEY: 'YOUR-API-KEY'
  ZENBOT_QUADRIGA_SECRET: 'YOUR-API-SECRET'
  ZENBOT_QUADRIGA_CLIENT_ID: 'YOUR-CLIENT-ID'

  # Wexnz exchange
  ZENBOT_WEXNZ_API_KEY: 'YOUR-API-KEY'
  ZENBOT_WEXNZ_SECRET: 'YOUR-API-SECRET'

  # Gemini exchange
  ZENBOT_GEMINI_API_KEY: 'YOUR-API-KEY'
  ZENBOT_GEMINI_SECRET: 'YOUR-API-SECRET'
  ZENBOT_GEMINI_SANDBOX: true

  # Hitbtc exchange
  ZENBOT_HITBTC_API_KEY: 'YOUR-API-KEY'
  ZENBOT_HITBTC_SECRET: 'YOUR-API-SECRET'

  ZENBOT_THEROCK_API_KEY: 'YOUR-API-KEY'
  ZENBOT_THEROCK_SECRET: 'YOUR-API-SECRET'

  # XMPP notifications
  ZENBOT_XMPP_ENABLE: false
  ZENBOT_XMPP_JID: 'trader@domain.com'
  ZENBOT_XMPP_PASSWORD: ''
  ZENBOT_XMPP_HOST: 'domain.com'
  ZENBOT_XMPP_PORT: 5222
  ZENBOT_XMPP_TO: 'MeMyselfAndI@domain.com'

  # Pushbullet notifications
  ZENBOT_PUSHBULLET_ENABLE: 'false'
  ZENBOT_PUSHBULLET_API_KEY: ''
  ZENBOT_PUSHBULLET_DEVICE_ID: ''

  # iffitt notifications
  ZENBOT_IFTTT_ENABLE: 'false'
  ZENBOT_IFTTT_API_KEY: ''
  ZENBOT_IFTTT_EVENT_NAME: 'zenbot'

  # Slack notifications
  ZENBOT_SLACK_ENABLE: 'false'
  ZENBOT_SLACK_WEBHOOK_URL: ''

  # ADAMANT notifications
  ZENBOT_ADAMANT_ENABLE: ''
  ZENBOT_ADAMANT_NODES: 'undefined'
  ZENBOT_ADAMANT_FROM_PASSPHRASE: ''
  ZENBOT_ADAMANT_TO_ADDRESSES: 'undefined'

  # Discord notifications
  ZENBOT_DISCORD_ENABLE: 'false'
  ZENBOT_DISCORD_ID: ''
  ZENBOT_DISCORD_TOKEN: ''
  ZENBOT_DISCORD_USERNAME: 'Zenbot'
  ZENBOT_DISCORD_AVATAR_URL: ''
  # color as a decimal
  ZENBOT_DISCORD_COLOR: null

  # Prowl notifications
  ZENBOT_PROWL_ENABLE: 'false'
  ZENBOT_PROWL_KEY: ''

  # Textbelt notifications
  ZENBOT_TEXTBELT_ENABLE: 'false'
  ZENBOT_TEXTBELT_PHONE: ''
  ZENBOT_TEXTBELT_KEY: ''

  # Pushover
  ZENBOT_PUSHOVER_ENABLE: 'false'
  # create application and supply the token here
  ZENBOT_PUSHOVER_TOKEN: ''
  # this is your own user's key (not application related)
  ZENBOT_PUSHOVER_USER_KEY: ''
  # choose a priority to send zenbot messages with, see https://pushover.net/api#priority
  ZENBOT_PUSHOVER_PRIORITY: '0'

  # Telegram
  ZENBOT_TELEGRAM_ENABLE: 'false'
  ZENBOT_TELEGRAM_INTERACTIVE: 'false'
  ZENBOT_TELEGRAM_BOT_TOKEN: ""
  ZENBOT_TELEGRAM_CHAT_ID: ""

replicaCount: 1
image: "deviavir/zenbot:latest"
service:
  type: ClusterIP
  port: 17365
  externalPort: 17365

persistence:
  storageClass: ""
  accessModes: 
    - ReadWriteOnce
  size: "8Gi"

ingress:
  enabled: false
  annotations: []
  hostname: "zenbot.example.com"
  tls: false


# Dependenciy Charts - https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
mongodb:
  service:
    type: ClusterIP
  architecture: standalone
  auth:
    rootPassword:  ""
    username: "admin"
    password: ""
    database: "zenbot4"

  persistence:
    enabled: true
  #  existingClaim: "-"
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 8Gi
  #  mountPath: /bitnami/mongodb