apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "zenbot.fullname" . }}-simulations-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}